# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d3239dcf7420accaf744d775cf669d4"
name = "products-pull-push-app"
handle = "products-pull-push-app"
application_url = "https://graduation-grass-menus-ru.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://graduation-grass-menus-ru.trycloudflare.com/auth/callback", "https://graduation-grass-menus-ru.trycloudflare.com/auth/shopify/callback", "https://graduation-grass-menus-ru.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
